
import React from 'https://dev.jspm.io/react@16.13.1';
import ContentComponent from './any_content.js';
export default {
  'config': {"srcDir":".","ignore":[{},{},{},{},{},{}],"plugins":["sidebar","script"],"title":"TypeScript 入门教程","sidebar":["README.md",{"link":"introduction/README.md","children":["introduction/what-is-typescript.md","introduction/get-typescript.md","introduction/hello-typescript.md"]},{"link":"basics/README.md","children":["basics/primitive-data-types.md","basics/any.md","basics/type-inference.md","basics/union-types.md","basics/type-of-object-interfaces.md","basics/type-of-array.md","basics/type-of-function.md","basics/type-assertion.md","basics/declaration-files.md","basics/built-in-objects.md"]},{"link":"advanced/README.md","children":["advanced/type-aliases.md","advanced/string-literal-types.md","advanced/tuple.md","advanced/enum.md","advanced/class.md","advanced/class-and-interfaces.md","advanced/generics.md","advanced/declaration-merging.md","advanced/further-reading.md"]},{"link":"engineering/README.md","children":["engineering/lint.md","engineering/compiler-options.md"]},"thanks/README.md"]},
  'pagePath': "basics/any.md",
  'layoutPath': "_layout.tsx",
  'outputPath': "basics/any.html",
  'title': "任意值",
  'sidebar': [{"title":"TypeScript 入门教程","link":"/index.html"},{"link":"/introduction/index.html","children":[{"title":"什么是 TypeScript","link":"/introduction/what-is-typescript.html"},{"title":"安装 TypeScript","link":"/introduction/get-typescript.html"},{"title":"Hello TypeScript","link":"/introduction/hello-typescript.html"}],"title":"简介"},{"link":"/basics/index.html","children":[{"title":"原始数据类型","link":"/basics/primitive-data-types.html"},{"title":"任意值","link":"/basics/any.html"},{"title":"类型推论","link":"/basics/type-inference.html"},{"title":"联合类型","link":"/basics/union-types.html"},{"title":"对象的类型——接口","link":"/basics/type-of-object-interfaces.html"},{"title":"数组的类型","link":"/basics/type-of-array.html"},{"title":"函数的类型","link":"/basics/type-of-function.html"},{"title":"类型断言","link":"/basics/type-assertion.html"},{"title":"声明文件","link":"/basics/declaration-files.html"},{"title":"内置对象","link":"/basics/built-in-objects.html"}],"title":"基础"},{"link":"/advanced/index.html","children":[{"title":"类型别名","link":"/advanced/type-aliases.html"},{"title":"字符串字面量类型","link":"/advanced/string-literal-types.html"},{"title":"元组","link":"/advanced/tuple.html"},{"title":"枚举","link":"/advanced/enum.html"},{"title":"类","link":"/advanced/class.html"},{"title":"类与接口","link":"/advanced/class-and-interfaces.html"},{"title":"泛型","link":"/advanced/generics.html"},{"title":"声明合并","link":"/advanced/declaration-merging.html"},{"title":"扩展阅读","link":"/advanced/further-reading.html"}],"title":"进阶"},{"link":"/engineering/index.html","children":[{"title":"代码检查","link":"/engineering/lint.html"},{"title":"编译选项","link":"/engineering/compiler-options.html"}],"title":"工程"},{"title":"感谢","link":"/thanks/index.html"}],
  content: React.createElement(ContentComponent),
  script: React.createElement('script', { type: 'module', src: '/main.js' })
}
